#! /bin/bash

# Declare destination dir for AllTest in 
# one place so it is easy to modify
REPO=$GIT_HOME/prog270-calvert-2016

# Declare destination for CSS, JavaScript and Images
CSS_JS_IMAGE=$REPO/ApacheHelpers

# Copy AllTest
cp -r ~/Documents/AllTest $REPO/

# Ensure destination dir exists for CSS, JS and Images
if [ ! -d "$CSS_JS_IMAGE" ]; then
	mkdir -p $CSS_JS_IMAGE
else
	echo $CSS_JS_IMAGE already exists
fi

# Copy CSS, JavaScript and Images
cp -ruv /var/www/html/css $CSS_JS_IMAGE/.
cp -ruv /var/www/html/images $CSS_JS_IMAGE/.
cp -ruv /var/www/html/js $CSS_JS_IMAGE/.
cp -uv /var/www/html/clean $CSS_JS_IMAGE/.
